### ISSUE TITLE
Paper's Table 1 Prac-MDL-COMP vs Cross-validation

### ISSUE THREAD

**Issue by kobybibas** [csinva/mdl-complexity#1]
Hi,
I found your paper very interesting and this repository be very helpful.

I'm trying to reproduce "Table 1. Prac-MDL-COMP vs Cross-validation for a range of datasets when the training data is limited."
I looked at submit_real_data_jobs.py file, but not sure how to execute it.
Is it the right file for Table 1? Where should I put the data?

And another general question:
Prac-MDL-COMP (paper's equation 11) depends on \sigma^2. 
How do you estimate it?

Thanks again,
Koby

**Comment by csinva** [comment]
Hi, thanks for your interest! 

Yes `submit_real_data_jobs.py` is the correct file! I've cleaned it up to be a little easier to use (before it was using some tricks with Slurm to parallelize the computation). This file basically specifies some different hyperparameters and then calls `fit.py`, where the real magic happens, so if you're curious that's probably the place to look for more details. The data will be downloaded and put in the right place automatically (thanks to the pmlb package).

Sigma^2 is calculate using unbiased estimator (based on the residuals of the OLS estimator) - see lines 108-113 of the file `fit.py`.
